export const INSERT_TO_CART = 'INSERT_TO_CART'
export const GET_CART_BY_USER_ID = 'GET_CART_BY_USER_ID'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const UPDATE_PRODUCT_FROM_CART = 'UPDATE_PRODUCT_FROM_CART'

