export const GET_AUTHENTICATED_SHOP = 'GET_AUTHENTICATED_SHOP'
export const CREATE_SHOP = 'CREATE_SHOP'
export const GET_SHOP_BY_NAME='GET_SHOP_BY_NAME'
export const GET_SHOP_BY_NAME_TWO='GET_SHOP_BY_NAME_TWO'
export const GET_SHOP_BY_USER_ID='GET_SHOP_BY_USER_ID'

