
export const GET_PRODUCTS_FOR_SHOP = 'GET_PRODUCTS_FOR_SHOP'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const GET_PRODUCTS_ALL = 'GET_PRODUCTS_ALL'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME'

