
  
//user reducer types
export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const GET_SELECTED_USER = 'GET_SELECTED_USER'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER'
export const CHANGE_MODE = 'CHANGE_MODE'
export const CREATE_ORDER = 'CREATE_ORDER'
export const GET_ORDER_SUMMARY = 'GET_ORDER_SUMMARY'
export const MARK_FAVORITE = 'MARK_FAVORITE'
export const MARK_UNFAVORITE = 'MARK_UNFAVORITE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_CUSTOMER='CREATE_CUSTOMER'

//Shop reducer types 
export const CREATE_SHOP='CREATE_SHOP'

export const LOGIN_SHOP = 'LOGIN_SHOP'
export const SIGNUP_SHOP = 'SIGNUP_SHOP'
export const GET_AUTHENTICATED_SHOP = 'GET_AUTHENTICATED_SHOP'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_SHOP_DATA = 'GET_SHOP_DATA'
export const GET_SHOP_PRODUCTS = 'GET_SHOP_PRODUCTS'
export const EDIT_SHOP_PROFILE = 'EDIT_SHOP_PROFILE'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const LOGOUT_SHOP = 'LOGOUT_SHOP'
export const GET_PRODUCT='GET_PRODUCT'

//errors reducer types 
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'
export const SET_LOGIN_REST_ERROR = 'SET_LOGIN_REST_ERROR'
export const CLEAR_LOGIN_REST_ERROR = 'CLEAR_LOGIN_REST_ERROR'
