//user reducer types
export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const GET_SELECTED_USER = 'GET_SELECTED_USER'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER'
export const CHANGE_MODE = 'CHANGE_MODE'
export const CREATE_ORDER = 'CREATE_ORDER'
export const GET_ORDER_SUMMARY = 'GET_ORDER_SUMMARY'
export const MARK_FAVORITE = 'MARK_FAVORITE'
export const MARK_UNFAVORITE = 'MARK_UNFAVORITE'
export const LOCATION_FILTER = 'LOCATION_FILTER'
export const LOGOUT_USER = 'LOGOUT_USER'

//Shop reducer types 
export const LOGIN_Shop = 'LOGIN_Shop'
export const SIGNUP_Shop = 'SIGNUP_Shop'
export const GET_AUTHENTICATED_Shop = 'GET_AUTHENTICATED_Shop'
export const GET_ALL_Shops = 'GET_ALL_Shops'
export const GET_Shop_DATA = 'GET_Shop_DATA'
export const EDIT_Shop_PROFILE = 'EDIT_Shop_PROFILE'
export const ADD_DISH = 'ADD_DISH'
export const ADD_TO_CART = 'ADD_TO_CART'
export const EMPTY_CART = 'EMPTY_CART'
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'
export const EDIT_DISH = 'EDIT_DISH'
export const LOGOUT_Shop = 'LOGOUT_Shop'

//errors reducer types 
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'
export const SET_LOGIN_REST_ERROR = 'SET_LOGIN_REST_ERROR'
export const CLEAR_LOGIN_REST_ERROR = 'CLEAR_LOGIN_REST_ERROR'
